FROM --  openjdk:17
WORKDIR -- /app
COPY  --     target/ecommerce-backend-0.0.1-SNAPSHOT.jar /app/ecommerce-backend-0.0.1-SNAPSHOT.jar
ENTRYPOINT    ["java","-jar","ecommerce-backend-0.0.1-SNAPSHOT.jar"]
EXPOSE -- 8080
